### ISSUE TITLE
can you create mp4remuxer graphic interface something like mkvtoolnixgui ?

### ISSUE THREAD

**Issue by YagneshDave** [KyleLeMarbe/DolbyVisionMuxer#1]
i only want to add audio track to already converted dv mp4 file so my TV's Kodi can play it 
something like mkvtoolnixgui but for DV mp4 files
https://www.videohelp.com/software/MP4Muxer

**Comment by Kyle-LeMarbe** [comment]
I'm not creating a GUI at this time. The command line questions work just fine for now and allows the script to run with minimal overhead.
